CC=g++

all: ultralewicowe srodek_drzewa
	
ultralewicowe: ultralewicowe.cpp
	$(CC) -o ultralewicowe ultralewicowe.cpp

srodek_drzewa: srodek_drzewa.cpp
	$(CC) -o srodek_drzewa srodek_drzewa.cpp

clean:
	rm -f *.o ultralewicowe srodek_drzewa