CC=g++

all: rejs rejs2 zlewki
	
rejs: rejs.cpp
	$(CC) -o rejs rejs.cpp

rejs2: rejs2.cpp
	$(CC) -o rejs2 rejs2.cpp

zlewki: zlewki.cpp
	$(CC) -o zlewki zlewki.cpp

clean:
	rm -f *.o rejs rejs2 zlewki